engines:
  # Fails
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  # Fails locally
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    # Fails with: comparison of Fixnum with String failed
      mass_threshold: 20
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-4-1
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - Gemfile.lock
exclude_paths:
- .codeclimate.yml
- .csslintrc
- .eslintrc
- bin/**/*
- config/**/*
- db/**/*
- features/**/*
- script/**/*
- spec/**/*
- vendor/**/*
