require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0

Rails:
  Enabled: true

Layout/LineLength:
  Max: 160

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/ModuleLength:
  CountComments: false
  Max: 300

Naming/VariableNumber:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
