# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "aliases_disciplines", :id => false, :force => true do |t|
    t.column "discipline_id", :integer, :default => 0, :null => false
    t.column "alias", :string, :limit => 64, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "aliases_disciplines", ["alias"], :name => "idx_alias"
  add_index "aliases_disciplines", ["discipline_id"], :name => "idx_discipline_id"

  create_table "disciplines", :force => true do |t|
    t.column "name", :string, :limit => 64, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "events", :force => true do |t|
    t.column "promoter_id", :integer
    t.column "parent_id", :integer
    t.column "city", :string, :limit => 128
    t.column "date", :date
    t.column "discipline", :string, :limit => 32
    t.column "flyer", :string
    t.column "name", :string
    t.column "notes", :string, :default => ""
    t.column "sanctioned_by", :string
    t.column "state", :string, :limit => 64
    t.column "type", :string, :limit => 32, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "flyer_approved", :boolean, :default => false, :null => false
    t.column "cancelled", :boolean, :default => false
    t.column "notification", :boolean, :default => true
  end

  add_index "events", ["date"], :name => "idx_date"
  add_index "events", ["discipline"], :name => "idx_disciplined"
  add_index "events", ["parent_id"], :name => "parent_id"
  add_index "events", ["promoter_id"], :name => "idx_promoter_id"
  add_index "events", ["type"], :name => "idx_type"

  create_table "promoters", :force => true do |t|
    t.column "email", :string
    t.column "name", :string, :default => "", :null => false
    t.column "phone", :string
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "promoters", ["name", "email", "phone"], :name => "promoter_info", :unique => true
  add_index "promoters", ["name"], :name => "idx_name"

  create_table "users", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "username", :string, :default => "", :null => false
    t.column "password", :string, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "users", ["username"], :name => "idx_alias", :unique => true

end
