# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "aliases", :force => true do |t|
    t.column "alias", :string
    t.column "created_at", :datetime
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "name", :string
    t.column "racer_id", :integer
    t.column "team_id", :integer
    t.column "updated_at", :datetime
  end

  add_index "aliases", ["name"], :name => "idx_name", :unique => true
  add_index "aliases", ["alias"], :name => "idx_id"
  add_index "aliases", ["racer_id"], :name => "idx_racer_id"
  add_index "aliases", ["team_id"], :name => "idx_team_id"

  create_table "aliases_disciplines", :id => false, :force => true do |t|
    t.column "discipline_id", :integer, :default => 0, :null => false
    t.column "alias", :string, :limit => 64, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "aliases_disciplines", ["alias"], :name => "idx_alias"
  add_index "aliases_disciplines", ["discipline_id"], :name => "idx_discipline_id"

  create_table "disciplines", :force => true do |t|
    t.column "name", :string, :limit => 64, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "events", :force => true do |t|
    t.column "promoter_id", :integer
    t.column "parent_id", :integer
    t.column "city", :string, :limit => 128
    t.column "date", :date
    t.column "discipline", :string, :limit => 32
    t.column "flyer", :string
    t.column "name", :string
    t.column "notes", :string, :default => ""
    t.column "sanctioned_by", :string
    t.column "state", :string, :limit => 64
    t.column "type", :string, :limit => 32, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "flyer_approved", :boolean, :default => false, :null => false
    t.column "cancelled", :boolean, :default => false
    t.column "notification", :boolean, :default => true
  end

  add_index "events", ["date"], :name => "idx_date"
  add_index "events", ["discipline"], :name => "idx_disciplined"
  add_index "events", ["parent_id"], :name => "parent_id"
  add_index "events", ["promoter_id"], :name => "idx_promoter_id"
  add_index "events", ["type"], :name => "idx_type"

  create_table "promoters", :force => true do |t|
    t.column "email", :string
    t.column "name", :string, :default => "", :null => false
    t.column "phone", :string
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "promoters", ["name", "email", "phone"], :name => "promoter_info", :unique => true
  add_index "promoters", ["name"], :name => "idx_name"

  create_table "racers", :force => true do |t|
    t.column "age", :integer
    t.column "ccx_category", :string
    t.column "ccx_number", :string
    t.column "cell_fax", :string
    t.column "city", :string, :limit => 128
    t.column "created_at", :datetime
    t.column "date_of_birth", :date
    t.column "dh_category", :string
    t.column "dh_number", :string
    t.column "email", :string
    t.column "first_name", :string, :limit => 64
    t.column "gender", :string, :limit => 2
    t.column "home_phone", :string
    t.column "last_name", :string
    t.column "license", :string, :limit => 64
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "mtb_category", :string
    t.column "notes", :string
    t.column "obra_member_on", :date
    t.column "obra_member", :boolean, :default => true, :null => false
    t.column "occupation", :string
    t.column "road_category", :string
    t.column "road_number", :string
    t.column "state", :string, :limit => 64
    t.column "street", :string
    t.column "team_id", :integer
    t.column "track_category", :string
    t.column "track_number", :string
    t.column "updated_at", :datetime
    t.column "work_phone", :string
    t.column "xc_number", :string
    t.column "zip", :string
  end

  add_index "racers", ["road_number"], :name => "idx_road_number", :unique => true
  add_index "racers", ["ccx_number"], :name => "idx_ccx_number", :unique => true
  add_index "racers", ["dh_number"], :name => "idx_dh_number", :unique => true
  add_index "racers", ["track_number"], :name => "idx_track_number", :unique => true
  add_index "racers", ["last_name"], :name => "idx_last_name"
  add_index "racers", ["first_name"], :name => "idx_first_name"
  add_index "racers", ["team_id"], :name => "idx_team_id"

  create_table "teams", :force => true do |t|
    t.column "city", :string, :limit => 128
    t.column "created_at", :datetime
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "name", :string, :default => "", :null => false
    t.column "notes", :string
    t.column "obra_member", :boolean, :default => false
    t.column "state", :string, :limit => 64
    t.column "updated_at", :datetime
  end

  add_index "teams", ["name"], :name => "idx_name", :unique => true

  create_table "users", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "username", :string, :default => "", :null => false
    t.column "password", :string, :default => "", :null => false
    t.column "lock_version", :integer, :default => 0, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "users", ["username"], :name => "idx_alias", :unique => true

end
