#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

ActionMailer::Base.template_root = "#{RAILS_ROOT}/app/views"
ActionMailer::Base.delivery_method = :sendmail

File.foreach(File.dirname(__FILE__) + '/email_addresses') do |recipient|
  puts(recipient)
  announcement_email = AnnouncementMailer.create_announcement(recipient)
  announcement_email.reply_to = 'Yann Blindert <nevens42@yahoo.com>'
  AnnouncementMailer.deliver(announcement_email)
end