#!/bin/bash

export PATH=$PATH:/usr/local/bin
export HOME=/var/lib/mailman

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

cd  /var/www/rails/obra/current

export NEWRELIC_ENABLE=false
bundle exec /var/www/rails/obra/current/script/rails runner -e "production" "MailingListMailer.receive(STDIN.read)" >> /var/log/mailman_archiver.log 2>&1
