#!/bin/bash

echo `date` >> /var/log/mailman_archiver.log 2>&1

export PATH=$PATH:/usr/local/bin
export HOME=/home/app

source "/home/app/.rvm/scripts/rvm" 2>&1

cd /var/www/rails/obra/current

export NEWRELIC_ENABLE=false
bundle exec rails runner -e "production" "MailingListMailer.receive(STDIN.read)" >> /var/log/mailman_archiver.log 2>&1
