#! /usr/bin/env ruby

`./script/local`
puts `mysql -u root -e 'set foreign_key_checks = 0; drop database if exists racing_on_rails_development; drop database if exists racing_on_rails_test'`
puts `mysql -u root < db/grants.sql`
puts `DISABLE_SPRING=1 rake db:setup RAILS_ENV=test`
puts `DISABLE_SPRING=1 rake db:setup`
(1..7).each do |index|
  puts `mysql -u root -e 'set foreign_key_checks = 0; drop database if exists racing_on_rails_test#{index}'`
end

puts `DISABLE_SPRING=1 rake parallel:create`
puts `DISABLE_SPRING=1 rake parallel:prepare`

[ "aba", "atra", "mbra", "nabra", "obra", "wsba" ].each do |association|
  puts association
  `./script/local #{association}`
  puts "Create databases"
  if association == "nabra"
    puts `mysql -u root -e 'grant all privileges on nabra_development.* to 'ror_development'@'localhost';'`
  else
    puts `mysql -u root -e 'grant all privileges on #{association}_development.* to '#{association}_development'@'localhost';'`
  end
  puts %x{mysql -u root -e 'grant all privileges on `#{association}_test`.* to #{association}_test@localhost'}
  puts %x{mysql -u root -e 'grant all privileges on `#{association}_test%`.* to #{association}_test@localhost'}
  puts `mysql -u root -e 'set foreign_key_checks = 0; drop database if exists #{association}_development'`
  puts `mysql -u root -e 'set foreign_key_checks = 0; drop database if exists #{association}_test'`
  (1..7).each do |index|
    puts `mysql -u root -e 'set foreign_key_checks = 0; drop database if exists #{association}_test#{index}'`
  end
  puts `DISABLE_SPRING=1 rake db:setup RAILS_ENV=test`
  puts `DISABLE_SPRING=1 rake db:setup`
  puts `DISABLE_SPRING=1 rake parallel:create`
  puts `DISABLE_SPRING=1 rake parallel:prepare`
end
