#! /usr/bin/env ruby
# frozen_string_literal: true

%w[ obra aba mbra wsba ].each do |association|
  puts "Deploy #{association}"
  `script/local #{association}`
  puts `cap production deploy`
  puts `cap production puma:stop`
  puts `cap production puma:start`
end
