#! /usr/bin/env ruby

# [ "aba", "atra", "mbra", "nabra", "obra", "wsba" ].each do |association|
#   puts "Deploy #{association}"
#   `script/local #{association}`
#   puts `cap deploy:migrations`
# end

[ "aba", "atra", "mbra", "nabra", "obra", "wsba" ].each do |association|
  puts "Clean up #{association}"
  `script/local #{association}`
  puts `cap deploy:cleanup`
end
