#! /usr/bin/env ruby

# Simple script to switch local directories for dev

require "fileutils"

association = ARGV[0]

if File.symlink?("local")
  FileUtils.rm "local"
end

if File.symlink?("public/local")
  FileUtils.rm "public/local"
end

if !association.nil?
  `ln -s ../racing_on_rails_local/#{association} local`
  `ln -s ../../racing_on_rails_local/#{association}/public public/local`
end

if association == "obra" || association == "nabra"
  if !File.symlink?("lib/registration_engine") && !File.directory?("lib/registration_engine.disabled")
    FileUtils.mv "lib/registration_engine", "lib/registration_engine.disabled"
  end
  if !File.exist?("lib/registration_engine")
    `ln -s ../../registration_engine lib/registration_engine`
  end
else
  if File.symlink?("lib/registration_engine") && File.directory?("lib/registration_engine.disabled")
    FileUtils.rm "lib/registration_engine"
    FileUtils.mv "lib/registration_engine.disabled", "lib/registration_engine"
  end
end
