#! /usr/bin/env ruby

# Simple script to switch local directories for dev

require "fileutils"

`spring stop`

[ "local", "public/local" ].each do |dir_name|
  if File.symlink?(dir_name)
    FileUtils.rm dir_name
  end
end

if Dir.exist?("tmp/cache/assets")
  FileUtils.rm_rf "tmp/cache/assets"
end

association = ARGV[0]

if !association.nil?
  `ln -s ../racing_on_rails_local/#{association} local`
  `ln -s ../../racing_on_rails_local/#{association}/public public/local`
end

if association == "obra"
  if !File.exist?("lib/registration_engine")
    `ln -s ../../registration_engine lib/registration_engine`
  end
else
  if File.exist?("lib/registration_engine")
    FileUtils.rm "lib/registration_engine"
  end
end
