#!/bin/bash

set -e

if [ "$DB" = '1' ]; then
  DISABLE_SPRING=1 bundle exec rake db:migrate parallel:prepare
fi

DISABLE_SPRING=1 bundle exec rake test:ruby
RECORD_RUNTIME=true DISABLE_SPRING=1 bundle exec rake parallel:test

bundle exec parallel_test lib/registration_engine/test/{controllers,helpers,integration,mailers,models}
DISABLE_SPRING=1 bundle exec rake test:acceptance
bundle exec rake registration_engine:test:acceptance
