#!/bin/bash

set -e

if [ "$DB" = '1' ]; then
  DISABLE_SPRING=1 bundle exec rake db:migrate parallel:prepare
fi

DISABLE_SPRING=1 bundle exec rake test:ruby
bundle exec rails test --exclude=registration_engine/test/acceptance test registration_engine/test

# bundle exec parallel_test registration_engine/test/{controllers,helpers,integration,mailers,models}
DISABLE_SPRING=1 bundle exec rake test:acceptance
bundle exec rake registration_engine:test:acceptance
